server {
	server_name CGI;
	listen 8080;
	host localhost;
	root websites/CGI_test;
	index index.html;
	client_max_body_size 1000000000;
    location / {
        root websites/CGI_test;
        index index.html;
        allow_methods GET;
        autoindex off;
    }
    location /upload {
        root websites/CGI_test/upload;
        upload_store websites/CGI_test/upload;
        allow_methods POST;
    }
    location /deletable {
        root websites/CGI_test/deletable;
        allow_methods GET DELETE;
        autoindex on;
    }
    location /cgi-bin {
        root websites/CGI_test/cgi-bin;
        cgi .py /opt/pyenv/versions/3.13.1/bin/python3;
        cgi .sh /bin/bash;
        allow_methods GET POST;
    }
    location /js {
        root websites/CGI_test/js;
        allow_methods GET;
    }
    location /style.css {
        root websites/CGI_test;
        allow_methods GET;
    }
}