server {
	server_name white;
	listen 8080;
	host localhost;
	root websites/white;
	index index.html;
	client_max_body_size 100000000;
	location / {
		root websites/white;
		index index.html;
		allow_methods GET;
		autoindex off;
	}
	location /images {
		root websites/white/images;
		allow_methods GET;
		autoindex off;
	}
	location /style.css {
        root websites/white;
        allow_methods GET;
    }
}

server {
	server_name blac;
	listen 8081;
	host localhost;
	root websites/black;
	index index.html;
	client_max_body_size 100000000;
	location / {
		root websites/black;
		index index.html;
		allow_methods GET;
		autoindex off;
	}
	location /images {
		root websites/black/images;
		allow_methods GET;
		autoindex off;
	}
	location /style.css {
        root websites/black;
        allow_methods GET;
    }
}
